spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/test}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: auth
  cache:
    type: hazelcast

  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}
      bindings:
#        input-topic:
#          destination: input-topic
#          group: input-group
#          content-type: application/json
        user-updated-out-0:
          destination: user-updated-event
#          content-type: application/json
#server:
#  port: 8080
#  servlet:
#    context-path: /v1/api/users

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # a day
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days


hazelcast:
  network:
    address: ${HAZELCAST_URL:localhost:5701}
